### ISSUE TITLE
Quick Rename not working

### ISSUE THREAD

**Issue by SamPlaysKeys** [SamPlaysKeys/Powershell-Onboarder#2]
Line 258 (linked below) of the base Onboarding.ps1 file does not function as intended, and returns a null value, rather than a text value that can be used by the Rename-Computer function. I will be testing internally to identify a different way to implement the Quick name-change, which may result in a small rebuild of the rename function.

https://github.com/SamPlaysKeys/Powershell-Onboarder/blob/7513ae81745cdc5a9d296ef638b0af0bf334192b/Onboarding.ps1#L258

**Comment by Farahad** [comment]
[Onboarding.txt](https://github.com/SamPlaysKeys/Powershell-Onboarder/files/9202450/Onboarding.txt)

if ($qrename.Checked) {
        $qname = $rename.Text + "-" + $cname
        Rename-Computer -NewName $qname
    }

$cname was a string while $rename was a text box object, so they couldn't be directly added. This solution converts $rename to a string before adding them, so that all the terms are of the same type.
